apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp2-ingress
  namespace: 
  labels:
    app: {{.Release.Name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: demo.nemkovich.by
      http:
        paths:
          - path: /app2
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80
