apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Release.Name }}-listener
    # the port that this service should serve on
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: NodePort