apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp1
  namespace: 
  labels:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: nemkovich.by
      http:
        paths:
          - path: /hello(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80
