apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp1
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: portfolio
  source:
    path   : "HelmCharts/MyChart1"
    repoURL: "https://github.com/softteco-inemkovich/argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      # parameters:
      # - name: "container.image"
      #   value: adv4000/app1:v3 # adv4000/app1:v3

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         
